CREATE TABLE if not exists pilot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    age        INTEGER                                 NOT NULL,
    CONSTRAINT pk_pilot PRIMARY KEY (id)
);

ALTER TABLE aircraft
    ADD pilot_id BIGINT;

ALTER TABLE aircraft
    ADD CONSTRAINT FK_AIRCRAFT_ON_PILOT FOREIGN KEY (pilot_id) REFERENCES pilot (id);

ALTER TABLE aircraft
    DROP COLUMN pilot;

CREATE SEQUENCE IF NOT EXISTS aircraft_id_seq;
ALTER TABLE aircraft
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE aircraft
    ALTER COLUMN id SET DEFAULT nextval('aircraft_id_seq');

ALTER SEQUENCE aircraft_id_seq OWNED BY aircraft.id;